{% set name = "gpyreg" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/GPyReg-{{ version }}.tar.gz
  sha256: 89410e759fbe0e015fc3416f5e28bd53591815ca96fb3ab66aadc43b1dfb9457

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5.1
    - numpy >=1.22.1
    - pytest >=6.2.5
    - pytest-rerunfailures >=10.2
    - scipy >=1.7.3

test:
  imports:
    - gpyreg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/GPyReg/
  doc_url: https://acerbilab.github.io/gpyreg/
  dev_url: https://github.com/acerbilab/gpyreg/
  summary: Lightweight package for Gaussian process regression.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Bobby-Huggins
    - lacerbi
